### ISSUE TITLE
How to get data from database up to display with dayspan-vuetify as a component

### ISSUE THREAD

**Issue by damqhieu** [ClickerMonkey/dayspan-vuetify#125]
In app.vue  i see `localStorage` and ` loadState` method . but i want it display from my data in database and I'm using dayspan-vuetify as a component . So how do
```
  <template>
  <v-app id="dayspan" v-cloak>
      <ds-calendar-app :calendar="calendar"  @event-create="eventCreate($event)"></ds-calendar-app>
    </v-app>
</v-app>
</template>
// <script>
import { mapActions } from 'vuex'
import { Calendar } from 'dayspan';
import 'vuetify/dist/vuetify.min.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
import 'dayspan-vuetify/dist/lib/dayspan-vuetify.min.css'

export default {
  name: 'Plan',
  data: () => ({
    calendar: Calendar.months(),
  }),
  methods: {
    ...mapActions(['setMiniDrawer']),
    eventCreate(event){
      console.log('event',event.schedule.toInput())
    }
  },
  created () {
    this.setMiniDrawer(false)
  },
  mounted () {

  }

}
</script>
```

**Comment by WolfgangAl** [comment]
Like I mentioned in my other message concerning #105, *saving* your events to the database most likely involves stringifying them into JSON and POSTing that data to your backend and have the backend store it in your database. HOW the backend does that (or, for that matter, whether or not you actually use a POST with JSON at all) is beyond the scope of this component; it has no opinion on how you should do that.

Likewise, *reading back* stored events into DaySpan-vuetify will most likely involve some GET request on your backend, which would collect event data from the database and send it back to the client. HOW this is done is again beyond the scope of this component. It only has one opinion:
1. If (and only IF) you want to use Parse.event to parse a simple, probably JSON.parse'd object into a DaySpan Event and Schedule object to add to a DaySpan calendar, DaySpan would really like it if you could make sure that that object contains a `data` member containing information like title, description, icon, et cetera and a `schedule` member containing schedule information which can be parsed by Parse.schedule.

Whether you agree and do it like that or roll your own parser for DaySpan Event and Schedule, when you and up with a collection of DaySpan Events you can use an `:events` binding on ds-calendar-app to automatically load that collection of Events into the calendar, or use DaySpan Calendar.addEvents (`this.$dayspan.addEvents`) to add either a collection of Events or indivudual Events programmatically.

By the way: app.vue isn't actually used when you use ds-calendar-app to display the calendar. It's only used for a standalone DaySpan-vuetify app. Its code serves mostly as an example, but will most likely not meet your requirements. (Like, saving to and loading from a database.)

**Comment by WolfgangAl** [comment]
You wouldn't. node_modules is managed by your package manager, like npm or yarn. It's unwise to touch anything in there. If you feel the need to change dayspan or dayspan-vuetify code, fork the repositories on GitHub and edit away. Changes you make to your own forks can be pushed back into GitHub (or your own repository provider). If you'd like to 'give back' to the main repository, you can use GitHub to create a pull request in this repository from your fork.

Just make sure you edit your package.json to point to your own repository instead of this one. (A good solution would be to make git submodule(s) in your project for your fork(s) and use a file reference like `'dayspan-vuetify': 'file:dayspan-vuetify-fork'`. This tells your package manager to look for the 'dayspan-vuetify' package in the folder 'dayspan-vuetify-fork'.)
