### ISSUE TITLE
404 on npm

### ISSUE THREAD

**Issue by cjtc** [ClickerMonkey/dayspan-vuetify#17]
Has this project moved? I get a 404 on npm: https://www.npmjs.com/search?q=dayspan-vuetify

**Comment by ClickerMonkey** [comment]
Greetings!

​I just published the current version to NPM (0.0.1) - but as noted in the
README - I will be making some (potentially) breaking changes​ over the
next week.

Thank you for your interest!

If you find any bugs or missing features, please let me know through GitHub!

Thanks


On Jul 18, 2018 8:34 PM, "CJ" <notifications@github.com> wrote:

Has this project moved? I get a 404 on npm: https://www.npmjs.com/search?
q=dayspan-vuetify

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ClickerMonkey/dayspan-vuetify/issues/17>, or mute the
thread
