### ISSUE TITLE
Unable to hide VToolbar

### ISSUE THREAD

**Issue by kavishgambhir** [ClickerMonkey/dayspan-vuetify#174]
How can I disable VToolbar inside the calendar component and use my own VToolbar with a router-view inside the VApp component?

**Comment by kavishgambhir** [comment]
cc @ClickerMonkey

**Comment by ClickerMonkey** [comment]
Use the ds-calendar component instead of ds-calendar-app

**Comment by x7ian** [comment]
I wanted to be able to anable or disable the toolbar according to some condition. 
In order to do this, I had to modify the CalendarApp component. 
First I added a new prop to it the following way:

```
useToolbar:
    {
      type: Boolean,
      default: true
    },
```

then I added a v-if condition to the v-toolbar component like this:

```
<v-toolbar app flat fixed
    v-if="useToolbar"
    class="ds-app-calendar-toolbar"
    color="white"
    :clipped-left="$vuetify.breakpoint.lgAndUp">

```
So now I can add a use-toolbar prop in my App.vue that shows or hides the toolbar:

```
<ds-calendar-app ref="app"
      :calendar="calendar"
      :read-only="readOnly"
      :use-toolbar="false"
      @change="saveState">

```
instead of false you can use a variable that can be then modified in a method if you want to be able to show or hide the toolbar based on a particular condition.
