### ISSUE TITLE
Support of database usage

### ISSUE THREAD

**Issue by kelvinau** [ClickerMonkey/dayspan-vuetify#42]
First of all, this is a great project. Thank you for making this nice library.
I see that currently the library uses only Local Storage to store "events".
Is there any plan to support an option for database instead?

I am happy to create a pull request for it too. And I believe the changes should be made in `src/app.vue` since that's the only place I can find `localStorage`?

**Comment by ClickerMonkey** [comment]
This library doesn't store events anywhere, but the example located in
src/app.vue does store it in localeStorage to keep things simple.

Just copy that code to get a simple version running. Instead of saving
events anytime the calendar changes, there are event-create, event-update,
and event-remove emitted from ds-calendar and ds-calendar-app. It would be
super easy to just hook into those events and make API calls to a database
there. The $event object passed to those events is a ds.Event object which
has a data property with the event details, and a schedule property which
is of type ds.Schedule. (ds = Dayspan)

**Comment by kelvinau** [comment]
Thanks for the direction! Will try it out.

**Comment by anjali89r** [comment]
@ClickerMonkey I was able to hook into event-create, event-update, and event-remove events and make API calls to the database. Now my challenge is to read the events from my db and put it out into the calendar. How would I achieve this?
Thanks.
