### ISSUE TITLE
[Vuetify] Multiple instances of Vue detected

### ISSUE THREAD

**Issue by rohsyl** [ClickerMonkey/dayspan-vuetify#73]
[Vuetify] Multiple instances of Vue detected
See https://github.com/vuetifyjs/vuetify/issues/4068

You probably need to update the version of vuetify to the 1.2.1.

**Comment by ClickerMonkey** [comment]
Thanks, I'll do an update and check it out.

**Comment by ClickerMonkey** [comment]
I verified that this Library is not bundling Vue with it, so I don't think it has anything to do with it. I'm not sure how Vuetify verifies multiple instances of Vue, I would expect Vue to be the one to validate that.

If you find out any info that contradicts what I've found, please commit and I'll re-open!

**Comment by italomaia** [comment]
Using version 1.2.6 and also got this error. Weird thing is that it is caused by simply importing Vue in the file where I load vuetify (which is not my main file)

**Comment by mtx-z** [comment]
Same error. Using : 

- `"dayspan-vuetify": "^0.3.2",`
- which use `"vuetify": "^1.1.1"` from package.json
- I have `1.2.9` installed

**Comment by nocke** [comment]
While switching from

`import Vue from 'vue/dist/vue.js';`
to
`import Vue from 'vue';`

avoids the `Multiple instances of Vue detected`...
...it also means, getting the `runtime-only` build (aka: the one without-template-parsing build), which is bad, because `vue-router` depends on this...  😕

There must be a better way...
